/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'moritalous' at '17/01/26 20:48' with Gradle 2.13
 *
 * @author moritalous, @date 17/01/26 20:48
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
